### ISSUE TITLE
Contact xpum test method

### ISSUE THREAD

**Issue by tomboy1551** [intel/xpumanager#1]
Hello

We are a company called Teratec located in Korea. PVC graphics cards to be launched next year are being prepared to develop a management solution.
I am interested in the released xpummanager.
We're going to test it after setting it up, but we don't have PVC. Is there a way to test it?
Is it possible to test with the Intel GPU on board in the laptop?

Thanks
CS.HAN

**Comment by eero-t** [comment]
I do not see why not.

XPUM uses oneAPI Level Zero Sysman APIs to collect the information: https://spec.oneapi.io/level-zero/latest/sysman/api.html

Level Zero is composed of two parts, an API frontend against which applications like XPU link against, and backend implementation (loaded dynamically by the frontend) which communicates with the kernel to actually provide the information.

What HW is supported and e.g. what metrics are provided for that, are dependent on what backend is present / installed.

L0 Sysman backend provided by the compute-runtime project: https://github.com/intel/compute-runtime/

Does also support Intel integrated GPUs, not just discrete ones. It does does much less for integrated ones though.

**Comment by eero-t** [comment]
@tomboy1551 If your question was answered, could you close this?
