### ISSUE TITLE
The dockerhub xpumanager container is too old for features like fetching the topology json via rest

### ISSUE THREAD

**Issue by uniemimu** [intel/xpumanager#17]
The dockerhub container is too old and features like the topology json fetching via the rest API don't seem to work with it. A fresh container works. New container would need to be pushed to dockerhub.

**Comment by donzh** [comment]
New container can be found at https://hub.docker.com/r/intel/xpumanager.

**Comment by eero-t** [comment]
@donzh Latest tag in DockerHub is v1.0.0 and is missing lot of other needed features from later releases.  A process to do DockerHub releases automatically from your Git repo releases would be good.  Otherwise there would need to be a bug like this filed for every release...

**Comment by donzh** [comment]
@eero-t Many thanks for your suggestion! We will take this suggestion.

**Comment by donzh** [comment]
We will release new container recently.
@eero-t Actually we can't automate the xpumanager container release because if we want to release container externally we need to go through an Intel internal process. This process can't be automated. Many thanks for your previous suggestion.

**Comment by eero-t** [comment]
Maybe you need to do things in a different order?   Security processes definitely should be requiring updating of insecure binary containers, not just updating & tagging sources.  And binary containers can include dependencies which need to be security-updates much more frequently than the actual application using them...

Note that some other Intel projects (e.g. k8s device plugins one) do quarterly releases which include also updating (multiple) containers in DockerHub.  Maybe you could ask help from them?
