### ISSUE TITLE
Use semantic versioning

### ISSUE THREAD

**Issue by eero-t** [intel/xpumanager#23]
Please use semantic versioning for releases: https://semver.org

(Instead of X.YSprintZ, X.YgoldenZ.W etc.)

**Comment by taotod** [comment]
@eero-t , many thanks for the suggestion. We will use the semantic versioning since next sprint.

**Comment by taotod** [comment]
Since 1.2.1, we adopt semantic versioning for the release. I close this issue. Many thanks for Eero's suggestion.
