### ISSUE TITLE
CentOS build container fails

### ISSUE THREAD

**Issue by jmechalas** [intel/xpumanager#3]
If you try to build XPUM using the CentOS build container it fails when running pip3:

```
      File "/tmp/pip-build-42dfn1zm/sphinxcontrib-openapi/.eggs/setuptools_scm-7.0.5-py3.6.egg/setuptools_scm/__init__.py", line 5
        from __future__ import annotations
        ^
    SyntaxError: future feature annotations is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-42dfn1zm/sphinxcontrib-openapi/
The command '/bin/sh -c pip3 --proxy=$http_proxy install grpcio-tools mistune==0.8.4 apispec apispec_webframeworks Sphinx     sphinx_rtd_theme sphinxcontrib-openapi apispec-webframeworks myst-parser marshmallow     prometheus-client flask flask_httpauth' returned a non-zero code: 1
```

The issue here is that Python support for import __future__ annotations was added in 3.7, but CentOS 8.4 ships with python 3.6. An easy fix here is to replace references to python3 here:

https://github.com/intel/xpumanager/blob/eb1d42772671e8d05e84e6f2d584bb5fb90292da/builder/Dockerfile.builder-centos#L12

with:

`python38 python38-devel python38-pip`

**Comment by ywang82** [comment]
Thanks @jmechalas. We also found this issue in our internal testing. The original docker build successed without any issues. But it failed recently. We have very similar fix as you suggested in the latest commit. [https://github.com/intel/xpumanager/blob/683038ce5131a0d65a8c13cfe06c3c223facfcef/builder/Dockerfile.builder-centos8](url)
