### ISSUE TITLE
xpumcli for Windows failed to work

### ISSUE THREAD

**Issue by wanglei1355** [intel/xpumanager#31]
The tool xpumcli.exe failed to execute with a dynamic library error. Either executable file download from [the releases page](https://github.com/intel/xpumanager/releases) or built from the source code has the same issue. 
I suppose ze_loader.dll is not consistent with ze_loader.lib. The ze_loader.dll on my machine is installed with the latest oneapi installer with version 1.2.3. So should the ze_loader.lib in the source code be updated?

![Capture](https://user-images.githubusercontent.com/49136985/221806164-ce0b9d88-ac30-443e-b729-db675d777dad.PNG)
![Capture1](https://user-images.githubusercontent.com/49136985/221806577-2fd867d5-2721-41f4-87c6-d4708c8245a0.PNG)

**Comment by wanglei1355** [comment]
I've found the reason. The ze_loader.dll from Driver-Release-64-bit_Intel_Data_Center_GPU_Win_10053 can work well with xpumcli.exe. Intel should update all the packages where this library is used.

**Comment by testdig** [comment]
@wanglei1355, thanks for reporting the issue. xpumcli depends on ze_loader with version 1.7.x and above, 1.2.3 is too old. Could you share the detail of "the latest oneapi installer"? Where did you download it?

**Comment by testdig** [comment]
@wanglei1355, I think your problem is solved and we will close this issue if not hearing you in the next two weeks.
