### ISSUE TITLE
Provide kustomize overlays for configuring k8s deployment

### ISSUE THREAD

**Issue by eero-t** [intel/xpumanager#32]
Current XPUM deployment enables and requires a lot of privileges, which are not really needed in most installations: https://github.com/intel/intel-device-plugins-for-kubernetes/issues/1342#issuecomment-1450293331

Deployment should be split into a basic base one, and overlays that add the extra features, similarly to how e.g. GPU plugin features are handled.

See:
* GPU plugin kustomize overlays: https://github.com/intel/intel-device-plugins-for-kubernetes/tree/main/deployments/gpu_plugin
* How to apply those: https://github.com/intel/intel-device-plugins-for-kubernetes/blob/main/cmd/gpu_plugin/README.md#install-to-nodes-with-intel-gpus-with-nfd
* K8s kustomize docs: https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/

**Comment by huiqiwa** [comment]
@eero-t , thank you for suggestion. Beginning with version 1.2.29, we've divided XPUM deployment into two parts.

**Comment by eero-t** [comment]
Thanks!

I would also suggest moving this README: https://github.com/intel/xpumanager/blob/master/deployment/README.md

Under the `docker` subdirectory, as it's only about Docker usage.

Then adding another README to the `kubernetes` subdirectory that shortly describes content under that directory.
