### ISSUE TITLE
Support for Arc GPUs?

### ISSUE THREAD

**Issue by dkalpakchi** [intel/xpumanager#35]
Hi!

Are there any plans to include at least partial support for Arc GPUs, which don't seem to be currently supported? It would be very useful to be able to see the output similar to `nvidia-smi` for NVIDIA GPUs, where one can (among other things) see:

- the temperature
- driver version
- total VRAM
- currently used VRAM along with the list of processes using that
- GPU utilization

If there are no plans for that currently, is there any documentation for any specific kind of API that one should consult in order to implement such a tool? I'm very new to Intel's stack, so any pointers would be much appreciated!

Thanks in advance for your time!

**Comment by taotod** [comment]
XPU Manager mainly targets Intel data center GPU, but the Level Zero interface is standard. You may install the Arc GPU driver and Level Zero package on your system. Most GPU telemetries listed by you can be gotten with XPU Manager. Please have a try.
