### ISSUE TITLE
request: info per subdevice

### ISSUE THREAD

**Issue by jxy** [intel/xpumanager#39]
Since each device may have multiple subdevices, it would be extremely useful if we can have info per subdevice. For example the output of `xpu-smi ps` could have an option to display per subdevice info, and other tools that have `-d,--device` option could accept `<num>.<num>` for specifying subdevices.

**Comment by fmiao2372** [comment]
xpu-smi stats and dump subcommand can show subdevice metrics. But currently, xpu smi ps can only display device level info throught sysfs/i915.

**Comment by jxy** [comment]
Did you close it because `xpu-smi ps` and `xpu-smi dump` may show per tile info now?
