### ISSUE TITLE
XPU-SMI not working with A770

### ISSUE THREAD

**Issue by fredlarochelle** [intel/xpumanager#50]
Running Ubuntu 22.04 with kernel 5.19.0-41-generic with an Intel Arc A770, XPU-SMI is not working. It mostly reports empty fields when running `xpu-smi stats -d 0` and when it does report something, the values don't make sense. For example, `GPU Memory Used`  doesn't concord with the values I am getting from IPEX (more than an order of magnitude of difference...).

It's probably not a driver issue on my system, XPU Manager is somewhat working and I have no trouble with IPEX.

If XPU Manager/XPU-SMI is not planning on any more comprehensive support for Arc cards, is there any other tools from Intel that would offer basic support for things like checking temperatures, memory usage, ... Also, not necessarily something concerning XPU Manager, but in general more documentation would be useful. For example, the documentation for XPU Manager is the only place I can find refering to updating the device firmware, is it something that needs to be done on Arc card? Or only on data center gpus?

**Comment by taotod** [comment]
@fredlarochelle With the public repository that Eero mentioned, the GPU power, temperature, GPU/GPU engine utilization, GPU memory used look good. I think that they are helpful to track your GPU and GPU workload status.
