### ISSUE TITLE
xpu-smi doesn't show anything about gpu utilization on a380

### ISSUE THREAD

**Issue by ytzhang1** [intel/xpumanager#62]
Here's my output, any idea what went wrong ?  I got the similar output on the UHD card.

$ xpu-smi stats -d 0
+-----------------------------+--------------------------------------------------------------------+
| Device ID                   | 0                                                                  |
+-----------------------------+--------------------------------------------------------------------+
| GPU Utilization (%)         |                                                                    |
| EU Array Active (%)         |                                                                    |
| EU Array Stall (%)          |                                                                    |
| EU Array Idle (%)           |                                                                    |
|                             |                                                                    |
| Compute Engine Util (%)     |                                                                    |
| Render Engine Util (%)      |                                                                    |
| Media Engine Util (%)       |                                                                    |
| Decoder Engine Util (%)     |                                                                    |
| Encoder Engine Util (%)     |                                                                    |
| Copy Engine Util (%)        |                                                                    |
| Media EM Engine Util (%)    |                                                                    |
| 3D Engine Util (%)          |                                                                    |
+-----------------------------+--------------------------------------------------------------------+
| Reset                       |                                                                    |
| Programming Errors          |                                                                    |
| Driver Errors               |                                                                    |
| Cache Errors Correctable    |                                                                    |
| Cache Errors Uncorrectable  |                                                                    |
| Mem Errors Correctable      |                                                                    |
| Mem Errors Uncorrectable    |                                                                    |
+-----------------------------+--------------------------------------------------------------------+
| GPU Power (W)               | 43                                                                 |
| GPU Frequency (MHz)         | 2400                                                               |
| GPU Core Temperature (C)    |                                                                    |
| GPU Memory Temperature (C)  |                                                                    |
| GPU Memory Read (kB/s)      |                                                                    |
| GPU Memory Write (kB/s)     |                                                                    |
| GPU Memory Bandwidth (%)    |                                                                    |
| GPU Memory Used (MiB)       | 2112                                                               |
| GPU Memory Util (%)         | 35                                                                 |
| Xe Link Throughput (kB/s)   |                                                                    |

**Comment by ytzhang1** [comment]
and similarly, if I try the dump option, here's the output. The GPU utilization and Core temperature are missing.

$ xpu-smi dump -d 0 -m 0,1,2,3
Timestamp, DeviceId, GPU Utilization (%), GPU Power (W), GPU Frequency (MHz), GPU Core Temperature (                                                                 Celsius Degree)
18:23:27.000,    0,     , 43.06, 2200,
18:23:28.000,    0,     , 39.98, 2450,
18:23:29.000,    0,     , 34.29, 2450,
18:23:30.000,    0,     , 42.96, 2400,
18:23:31.000,    0,     , 36.90, 2450,
18:23:32.000,    0,     , 42.38, 2450,
18:23:33.000,    0,     , 42.51, 2450,
18:23:34.000,    0,     , 31.11, 2300,
18:23:35.000,    0,     , 43.06, 2200,
18:23:36.000,    0,     , 40.26, 2450,
18:23:37.000,    0,     , 43.21, 2200,
18:23:38.000,    0,     , 40.58, 2450,
18:23:39.000,    0,     , 28.70, 2450,

**Comment by huiqiwa** [comment]
Hi @ytzhang1  Could you try to use root user to run xpu-smi?
