### ISSUE TITLE
xpu-smi unable to set powerlimit

### ISSUE THREAD

**Issue by vinitshenoy** [intel/xpumanager#63]
I am using Arc-770 and Ubuntu 20.04 with kernel 5.14.0-1034-oem.

I want to power limit the GPU TDP to 50W to see impact of GPU performance.
root@ubuntuserver20:/home# xpu-smi config -d 0 --powerlimit 50
Return: Succeed to set the power limit on GPU 0.

Message seems to indicate power-limit is successfully set.
root@ubuntuserver20:/home# xpu-smi config -d 0
+-------------+-------------------+----------------------------------------------------------------+
| Device Type | Device ID/Tile ID | Configuration                                                  |
+-------------+-------------------+----------------------------------------------------------------+
| GPU         | 0                 | Power Limit (w): 50                                            |
|                 |                    |   Valid Range: 1 to 0                                          |
|                 |                    |                                                                           |
|                 |                    | Memory ECC:                                                    |
|                 |                    |   Current:                                                           |
|                 |                    |   Pending:                                                          |
+-------------+-------------------+----------------------------------------------------------------+

However when I run the GPU workloads I still see the GPU consuming more than 50W of power. 

root@ubuntuserver20:/home/openvino# xpu-smi dump -d 0 -m 0,1,2
Timestamp,       DeviceId, GPU Utilization (%), GPU Power (W), GPU Frequency (MHz)
05:07:33.000,    0,              94.10,                      104.60,               2000
05:07:34.000,    0,              94.04,                      103.34,               2000
05:07:35.000,    0,              93.31,                      103.36,               2000
05:07:36.000,    0,              93.37,                      102.90,               2000
05:07:37.000,    0,              93.47,                      102.56,               2150

Am I missing something here?

**Comment by taotod** [comment]
Arc GPU is not officially supported by XPU Manager.
