### ISSUE TITLE
Contradictory support for Windows OS

### ISSUE THREAD

**Issue by dushyantRathore** [intel/xpumanager#65]
The official [README](https://github.com/intel/xpumanager/blob/master/README.md) mentions the support for only XPU Manager in Windows Server 2019/2022. On the other hand, [Releases](https://github.com/intel/xpumanager/releases) lists Windows under XPU-SMI only. Also, there is no xpumanager related asset for Windows.

**Comment by fmiao2372** [comment]
It's a bug in README and we will fix it in next sprint.  On Windows, only XPU-SMI/Library are supported. Thank you for your carefulness.
