### ISSUE TITLE
Container images on Docker Hub

### ISSUE THREAD

**Issue by mzernovx** [intel/xpumanager#67]
The latest version of container image available on docker hub [is v1.2.13](https://hub.docker.com/r/intel/xpumanager/tags). Will newer versions continue to be published?
If not, [which Dockerfile](https://github.com/intel/xpumanager/tree/master/deployment/docker) should be used and what are prerequisites prior to building the image? What is difference between `Dockerfile.ubuntu.22.04` and `Dockerfile.ubuntu.22.04.max`?

**Comment by huiqiwa** [comment]
Hi @mzernovx 
We choose to release stable versions in dockerhub. If you try using v1.2.13 and have any unmet needs, please feel free to provide feedback.

Dockerfile.ubuntu.22.04 and Dockerfile.ubuntu.22.04.max are respectively applicable to GPU card Flex and Max. 
You can refer to the comments in each file for the prerequisites.
# Prerequisite:
# ./build-deb/xpumanager_xxxxx+ubuntu22.04_amd64.deb
# ./requirements.txt (copy from rest)
# ./third-party-programs.txt

**Comment by mzernovx** [comment]
Hello @huiqiwa! Thank you for the explanation, if stable versions are ones that are in Dockerhub then it's good to go with them.
