### ISSUE TITLE
xpumcli/xpu-smi dump does not support PCIe read/write on EMR-SP MCC with Flex140 and Flex170

### ISSUE THREAD

**Issue by azril-ahmad** [intel/xpumanager#68]
I was trying to read the Flex140/170 PCIe read/write and observe that either xpumcli or xpu-smi does not support the PCIe reading under EMR-SP MCC with error that the CPU is not supported by PCM IIO tool. 

Below is the example of the error snapshot:
![image](https://github.com/intel/xpumanager/assets/90176387/16f2393f-4497-4945-a8c3-6193fc70835c)

**Comment by taotod** [comment]
XPU Manager reports the GPU PCIe throughput with Intel PCM library. I think that Intel PCM has not supported EMR-SP.
