### ISSUE TITLE
GPU temperature is not reported by Prometheus exporter fox Max 1100

### ISSUE THREAD

**Issue by pbchekin** [intel/xpumanager#75]
Steps to reproduce:

* Install the latest xpumanager (V1.2.29) as Kubernetes DaemonSet.
* Install the provided Grafana dashboard.

Result:

* Grafana shows metrics such as "GPU Utilization"
![image](https://github.com/intel/xpumanager/assets/1797803/38c0ac28-9fb5-46e5-a73f-f4af8c712518)

* Grafana shows "No data" for "GPU Temperature"
![image](https://github.com/intel/xpumanager/assets/1797803/a1458428-32d2-4d2b-b2a4-071442aa01e4)

GPU: Max 1100
Driver: Agama 775.20
xpumanager: 1.2.29

**Comment by fmiao2372** [comment]
Please use zello_sysman tool to firstly check whether Sysman temperature API can work not. Most missing metric issues are caused by the underlying driver or firmware. 
```
wget https://raw.githubusercontent.com/intel/compute-runtime/releases/23.48/level_zero/tools/test/black_box_tests/zello_sysman.cpp
g++ -O2 -Wall -o zello_sysman zello_sysman.cpp -lze_loader
sudo ./zello_sysman --temperature
```

**Comment by pbchekin** [comment]
> Please use zello_sysman tool to firstly check whether Sysman temperature API can work not.

```
 sudo ./zello_sysman --temperature
ZES_ENABLE_SYSMAN environment variable Not Set
Setting the environment variable ZES_ENABLE_SYSMAN 
ZES_ENABLE_SYSMAN environment variable Set
Device Name = Intel(R) Data Center GPU Max 1100
UUID: 
� � � 
       /    �        
Sysman Initialization done via zeInit

 ----  Temperature tests ---- 
ZE_RESULT_ERROR_UNINITIALIZED returned by zesDeviceEnumTemperatureSensors(device, &count, nullptr): testSysmanTemperature: 448
Could not retrieve Temperature domains
```

**Comment by fmiao2372** [comment]
Try the following steps and re-run zello_sysman
```
1. add modprobe.blacklist=intel_pmt in the /etc/default/grub file at GRUB_CMDLINE_LINUX_DEFAULT line 
2. run update-grub command  
3. reboot
4. sudo ./zello_sysman --temperature
```

**Comment by eero-t** [comment]
I'm assuming this is with the (public) i915-backport (out-of-tree DKMS) kernel driver.

Which kernel and what GPU related kernel driver (package) versions you're using?

(AFAIK temperature is out-of-band data and needs separate kernel module from the main kernel `i915` GPU driver. I think `intel_pmt` was old name for it, but I do not remember what's its replacement. @fmiao2372?)

**Comment by eero-t** [comment]
Tested somewhat older multi-GPU setup, and temperature works with it.

Kernel / HW related components that setup had:
* OS: Ubuntu 22.04.3 LTS
* i915 DKMS: 1.23.6.42.230425.56+i81-1
  - `/proc/modules` "compat" line lists: `mei_iaf,mei_gsc,pmt_telemetry,pmt_crashlog,pmt_class,i915,mei_me,intel_vsec,mei`
* kernel: 5.15.0-92-generic
* HW: Data Center GPU Max 1100 (0x0bda rev 2f)
* FW: pvc_guc_70.9.1

I have no idea which driver version is "Agama 775.20" but my user-space driver stacks are built from _public_ releases in: https://github.com/intel/

_Both_ my latest build from month ago:
- GMMlib:            intel-gmmlib-22.3.17
- SPIRV-SDK:         vulkan-sdk-1.3.275.0/vulkan-sdk-1.3.275.0 (headers/tools)
- SPIRV-LLVM:        libllvmspirvlib-14-dev:amd64:14.0.0-3ubuntu1 (Ubuntu package)
- OpenCL-Clang:      libopencl-clang-14-dev:amd64:14.0.0-4 (Ubuntu package)
- VC-intrinsics:     v0.16.0
- Graphics Compiler: igc-1.0.16161.0 (IGC)
- Level-Zero API:    v1.15.8
- compute-runtime:   23.52.28202.14

And e.g. an older build from last May:
- GMMlib:            intel-gmmlib-22.3.5
- SPIRV-SDK:         sdk-1.3.250.0/sdk-1.3.250.0 (headers/tools)
- SPIRV-LLVM:        libllvmspirvlib-12-dev:amd64:12.0.0-3 (Ubuntu package)
- OpenCL-Clang:      libopencl-clang-12-dev:amd64:12.0.0-3 (Ubuntu package)
- VC-intrinsics:     v0.13.0
- Graphics Compiler: igc-1.0.14207.2 (IGC)
- Level-Zero API:    v1.11.0
- compute-runtime:   23.17.26241.19

provide temperature data with `zello_sysman --temperature`.

=> Therefore I would expect any `compute-runtime` (providing the Sysman backend providing the GPU metrics) driver version between them (or newer) also to work fine, as long as you have the required FW & kernel drivers installed.

As you're using Ubuntu `intel-i915-dkms`, I assume you installed it from Intel driver repos: https://dgpu-docs.intel.com/driver/installation.html#ubuntu-install-steps

Sysman backend binary package in that repo is named `intel-level-zero-gpu`, and XPU Manager command line tool package is named as `xpu-smi`.

**Comment by pbchekin** [comment]
> I have no idea which driver version is "Agama 775.20"

This is _public_ rolling release: https://dgpu-docs.intel.com/releases/stable_775_20_20231219.html

**Comment by pbchekin** [comment]
Looks like the temperature readings do not work with the driver from public rolling release, but works with public LTS release. Closing this issue since it is more likely a driver issue.

**Comment by eero-t** [comment]
> > I have no idea which driver version is "Agama 775.20"
> 
> This is _public_ rolling release: https://dgpu-docs.intel.com/releases/stable_775_20_20231219.html

It says "stable release" (not "rolling" one)?

Page does list package versions, but only the `intel-opencl-icd` OpenCL driver package version `23.35.27191.42` corresponds to `compute-runtime` project release numbers.  L0 / Sysman `intel-level-zero-gpu` driver package version does use the same `27191` sub-number, so I think it's built from the compute-runtime sources  (as expected).

`23.35.27191.42` version is somewhere between `compute-runtime` versions that I had tested, therefore I would assume Sysman part to be OK (unless there was some fixed regression in between that just happens to be in this release). I.e. issue would be somewhere lower in the stack (kernel side).


> Looks like the temperature readings do not work with the driver from public rolling release, but works with public LTS release.  Closing this issue since it is more likely a driver issue.

I'm sure it's not XPUM issue, but unless you filed separate driver bug, I think it could be discussed here.

Did you get temperature metrics working with some driver version?

(I'm interested what was not working, and what fixed it.)

**Comment by pbchekin** [comment]
> It says "stable release" (not "rolling" one)?

This page https://dgpu-docs.intel.com/driver/installation.html#ubuntu-install-steps calls it "rolling stable release".

> Did you get temperature metrics working with some driver version?

Yes, as I wrote previously the temperature metrics work with LTS driver.

> (I'm interested what was not working, and what fixed it.)

Let's see if the issue will be fixed the next rolling stable driver release.

**Comment by eero-t** [comment]
Ah, this has links for them: https://dgpu-docs.intel.com/releases/index.html

Comparing the compute-runtime (Sysman) driver versions in them:
* production: 23.22.26516.34
* rolling stable: 23.35.27191.42
* LTS: 23.43.27642.38

And i915 kernel DKMS versions:
* production: 1.23.6.42.230425.56
* rolling stable: 1.23.9.11.231003.15
* LTS: 1.23.10.30.231129.29

=> LTS has the _latest_ kernel & user-space driver versions...

Did you install the whole stack, including kernel DKMS?

**Comment by pbchekin** [comment]
> Did you install the whole stack, including kernel DKMS?

I hope so. I just followed the installation instructions: `apt install -y linux-headers-$(uname -r) flex bison intel-fw-gpu intel-i915-dkms xpu-smi` plus level-zero, compute, and media runtimes.

**Comment by eero-t** [comment]
Ok, so it's unclear whether kernel or user-space side update fixed it.

(Especially as I had it working with components that were all older than ones in rolling stable, which were older than ones in LTS...)

**Comment by pbchekin** [comment]
> Ok, so it's unclear whether kernel or user-space side update fixed it.
> 
> (Especially as I had it working with components that were all older than ones in rolling stable, which were older than ones in LTS...)

Yes, but since XPUM works in a container with its own user-space environment (i have installed it as a Kubernetes DaemonSet) the only component on the host that matters is the driver, IMHO.

**Comment by eero-t** [comment]
Ok, if XPUM is in container, than indeed only kernel driver matters.  And you updated drivers only to the host, and did not touch XPUM container contents?

(In my tests, user-space drivers are built or installed to a container, not host.)

**Comment by eero-t** [comment]
Thanks, then the issue was indeed the kernel driver.
