### ISSUE TITLE
xpu-smi can be displayed like nvidia-smi

### ISSUE THREAD

**Issue by alanzhai219** [intel/xpumanager#78]
nvidia-smi can **directly** show the GPU status including but not limiting GPU utilization, Memory utilization, and running progress.
xpu-smi looks a bit hard to use.
Can your team improve the UX and UE?
Thanks.

**Comment by taotod** [comment]
xpu-smi dump command can show the GPU telemetry trending. Please try.

**Comment by alanzhai219** [comment]
> xpu-smi dump command can show the GPU telemetry trending. Please try. 

Could you provide the cmd to display like nvidia-smi default output?

**Comment by taotod** [comment]
No xpu-smi doesn't provide that. You may use xpu-smi stats and ps commands to get the info.

**Comment by alanzhai219** [comment]
> No xpu-smi doesn't provide that. You may use xpu-smi stats and ps commands to get the info. 

Could your team imitate it though competitors amd and Nvidia's xxx-smi is much easy to use?

**Comment by taotod** [comment]
It will be considered. Thanks for the suggestion.
